theme: jekyll-theme-tactile
title: "Regression Data Sets for Learning from Imbalanced Domains"
show_downloads: true
github:
  zip_url: https://github.com/paobranco/DataSets-IR/zipball/master
  tar_url: https://github.com/paobranco/DataSets-IR/tarball/master
